### ISSUE TITLE
Latest Sikkmod for dhewm3 ?

### ISSUE THREAD

**Issue by motorsep** [dhewm/dhewm3#120]
Just wondering if there is a port of latest Sikkmod to dhewm3.

**Comment by DanielGibson** [comment]
Maybe after release 1.4.0 I'll integrate the https://github.com/DanielGibson/dhewm3-mods thing and I might add Sikkmod to the supported mods, if it's not too hard and if the license permits it.
(There is GPL'ed code from Sikkpin at https://github.com/RobertBeckebans/Sikkpin-Breadcrumps-src and https://github.com/RobertBeckebans/Sikkpin-Feedback but I haven't checked yet if that actually contains Sikkmod)

**Comment by nbohr1more** [comment]
I would love to hear otherwise but I am under the impression that Sikkpin was not exactly following GPL license protocol when he built his project. I believe he did integrated shaders from whatever sources he found most beneficial whether they had permissive licenses or not. I think the bulk of the HDR code was publicly co-developed over at Doom3world.org but DOF, SSAO, and SSIL may all contain code derived from other authors and possibly even commercial projects (there is an SSAO method labeled Crysis) and he claimed that his ABAO method was stolen by another commercial project but this was never validated as I recall so even if Sikk had prior art the commercial entity could claim otherwise. I have no idea whether any of this has changed between his 1.2 release and the Feedback \  Breadcrumbs work but for the latter his skin shaders bear some resemblance to those used in Prey and he was researching getting his engine to work more like Prey so they could also be derivative. Again, if Sikk wants to stop in and flame me to bits for being wrong so be it... this is just what I've gleaned from a few discussions with other shader developers.

**Comment by DanielGibson** [comment]
If it's labeled "crysis" then probably he developed it following a paper released by crytek or something.. but I don't know and I guess with doom3world gone, it'll be impossible to reconstruct who contributed what under which license.

But I don't care very much about the shader code anyway.. just about the C++ code.
Like with the other mods I'd put the code (adapted to dhewm3) in that github repo so people can build sikkmod.dll or whatever from it and use it with the latest release of the mod (which contains the shaders).

So my GPL requirement is only for the C++ code, *not* for the assets (which includes shaders).

**Comment by nbohr1more** [comment]
That sounds reasonable.

FYI: The Breadcrumbs \ Feedback code on Github is fairly divergent from Vanilla Doom 3 if you didn't catch that from my last reply. I don't believe it will even render Vanilla Doom 3 maps properly as I recall. I have a copy of his breadcrumbs demo and assets if you would like me to upload it anyway. As I can tell, you would need to get the source from the Sikkmod 1.2 package at Moddb.

**Comment by DanielGibson** [comment]
The sikkmod source on moddb is under SDK license, not GPL, so I can't use that (at least not without Sikkpin's consent to re-license it under GPL).

**Comment by aFoxNamedMorris** [comment]
There is an old dhewm3 branch that I used to use for Sikkmod support:
https://github.com/alepulver/dhewm3

**Comment by deuxsonic** [comment]
Does dhewm3 make use of the soft shadows that RBDOOM-3-BFG uses as a result of the stuff with Carmack's Reverse?

**Comment by aFoxNamedMorris** [comment]
Only if you compile Sikkmod with it.

**Comment by DanielGibson** [comment]
dhewm3 doesn't use Carmack's Reverse, (which was used as a performance optimization with stencil shadows, not soft shadows).
But it uses stencil shadows *without* Carmack's Reverse and looks the same as the original game. The performance aspect is negligible for hardware that's less than 10years old.

I think sikkmod allows some kind of soft shadows, but I doubt they're the same as the ones in RBDoom3BFG.

**Comment by aFoxNamedMorris** [comment]
That is correct. Doom 3/Dhewm3 uses ARB shaders. All of the Sikkmod shaders, including the soft shadows, were written in ARB format. Doom 3: BFG Edition/RBdoom3BFG uses CG shader format, which the engine converts to HLSL, GLSL, or whatever your primary native 3D API is.

**Comment by nbohr1more** [comment]
There's far more to it than that. Sikkmod is blurring the existing stencil shadows, RBdoom3BFG replaces the native stencil shadows with shadow mapping.

**Comment by deuxsonic** [comment]
Yeah, because BFG still has hard-edged shadows where they're softter in RB. Thanks for explaining guys, I didn't know the background on all this. 
 


     On Saturday, October 17, 2015 8:16 AM, nbohr1more <notifications@github.com> wrote:
   

 There's far more to it than that. Sikkmod is blurring the existing stencil shadows, RBdoom3BFG replaces the native stencil shadows with shadow mapping.—

**Comment by aFoxNamedMorris** [comment]
Yeah, sorry. I was speaking in terms of practicality. Guess I should be more specific in the future. :P

**Comment by DanielGibson** [comment]
I wrote Sikkpin an E-Mail a week ago, asking him if he'd be willing to relicense Sikkmod under GPL, but haven't gotten an answer so far. Does anyone know if he's still alive and how he can be reached?

I also looked into his aforementioned breadcrumbs project, but it's missing lots of code from sikkmod, like lots of CVars to change default damage materials (I think), but also soft shadows (maybe he implemented those differently with access to the whole engine source). So it's not as easy as just copying the relevant code from breadcrumbs and calling it sikkmod-gpl :-/

**Comment by DanielGibson** [comment]
BTW, I didn't get a response from Sikkpin.
If someone has a way to contact him, please do, but I personally can't do any more about it.
Without his ok to relicense the Sikkmod C++ mod source under GPL there can be no Sikkmod for dhewm3 :-/

**Comment by eezstreet** [comment]
Going to bump this because I have some new information.

In 2011 I emailed Sikkpin and got permission to use Sikkmod's source code with a GPL licensed project. Attached is an image of the email that I received from "sikkpin@hotmail.com" which I believe is his email address at the time.

![image](https://github.com/dhewm/dhewm3/assets/1828421/16114ac8-d431-401d-9317-8b3d7c1dee69)

**Comment by DanielGibson** [comment]
Unfortunately, the restriction "can not be used in any commercial product" isn't compatible with the GPL, at least if it refers to the C++ code and not just the game data (or shaders)

**Comment by DanielGibson** [comment]
OTOH, *maybe* it could be interpreted as "You can use the C++ source under GPL, but must not use the rest (shaders, scripts, textures, ...) in commercial projects" - the C++ code without the shaders isn't overly useful for commercial projects anyway, but that interpretation would conform to the GPL at least

**Comment by eezstreet** [comment]
That’s pretty much exactly how I interpreted it.

Sent from my iPhone

On Oct 29, 2023, at 9:05 PM, Daniel Gibson ***@***.***> wrote:

﻿

OTOH, maybe it could be interpreted as "You can use the C++ source under GPL, but must not use the rest (shaders, scripts, textures, ...) in commercial projects" - the C++ code without the shaders isn't overly useful for commercial projects anyway, but that interpretation would conform to the GPL at least

**Comment by DanielGibson** [comment]
I merged Sikkmod to dhewm3-sdk: https://github.com/dhewm/dhewm3-sdk/tree/sikkmod

Haven't tested this at all yet, only made sure it builds (on Linux)

**Comment by DanielGibson** [comment]
By the way, I first merged Sikkmod v1.1 for the base game, then for d3xp, then Sikkmod v1.2 for the base game.
Apparently there was no Sikkmod v1.2 for d3xp, but if anyone wants to port the v1.2 changes to d3xp, the commit updating Sikkmod for the basegame from 1.1 to 1.2 should be useful.
(But note that it *may* require changes to the sikkmodd3xp gamedata as well, I don't know)

**Comment by DanielGibson** [comment]
this is released in 1.5.4 RC1, which could use some testing: https://github.com/dhewm/dhewm3/releases/tag/1.5.4_RC1
