### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [dhewm/dhewm3#126]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output.") ⇒ [LeakFile](https://github.com/dhewm/dhewm3/blob/657ad99bf185feb71199c6af097577d037e59d59/neo/tools/compilers/dmap/leakfile.cpp#L43)
- [ftell](http://pubs.opengroup.org/onlinepubs/9699919799/functions/ftell.html "Return a file offset.") ⇒ [idFileSystemLocal::DirectFileLength](https://github.com/dhewm/dhewm3/blob/657ad99bf185feb71199c6af097577d037e59d59/neo/framework/FileSystem.cpp#L650)

**Comment by DanielGibson** [comment]
dunno.. these are unlikely to fail, and LeakFile() is just for debugging anyway.

in how many other places is this not handled? could it be integrated without changing existing function/method signatures?

if this can be done without too many changes.. why not. but otherwise I think the gain is relatively small (doesn't this only happen if the filesystem is corrupted/full?)

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by DanielGibson** [comment]
you're not really responding to my comment.. are you a bot?

**Comment by elfring** [comment]
Are more software developers generally interested in improvements for exception handling?
