### ISSUE TITLE
Sound buffers?

### ISSUE THREAD

**Issue by wildweasel486** [dhewm/dhewm3#141]
One thing has always bothered me about id Tech 4 games - Doom 3, Quake 4, and Prey specifically; Wolfenstein doesn't seem to have this problem - and that's the way rapid-fire weapons sound. Under sustained fire, the machine gun, chaingun, and plasma rifle all sound as if they're "missing" their firing sounds every few shots. Other things suffer from this, too, like footstep noises. I suspect it's a problem with the sound buffer size and response times, but I can't find any console variables to set to fix it.

I'd asked about this on the Doomworld forums, but was directed to ask here instead; is there some oddity to the id Tech 4 sound engine at work here? I can confirm that it happens in both vanilla Doom 3 (Windows 1.3.1) and in a release build of dhewm3 from last week.

**Comment by hemebond** [comment]
Apparently this is an issue with sound system synchronisation and has apparently been fixed in the Doom 3 BFG Edition.

**Comment by gabrielcuvillier** [comment]
Maybe you could try to tweak the "com_asyncSound" cvar to sse if there is any difference (need to be done at compilation or startup time):

0: mix sound inline (in the main thread)
1: memory mapped async mix (separate thread, default on windows)
2: callback mixing (not sure if it is working)
3: write async mix (separate thread, default on Linux)

**Comment by hemebond** [comment]
Default was 3. No difference with 0 and 1. No sound at all with 2.

I did see mention of a cvar that could "fix" it but apparently it caused cutscene audio to desync.

**Comment by gabrielcuvillier** [comment]
Ok, this is maybe related to the specific OpenAL implementation being used also

**Comment by hemebond** [comment]
BTW, this is the comment that mentioned a variable for audio sync https://steamcommunity.com/app/208200/discussions/0/343786746010619195/#c343787920131961205

**Comment by thoughtartist** [comment]
This has always happened to me throughout Win XP and Win 10 and two different motherboards and Soundblaster cards happens now with the source port. I will test more. After playing awhile, it is quite immersion breaking, especially when I have modded the weapon sounds and no matter what, have a skip.

**Comment by DanielGibson** [comment]
Is this even a bug?
As it happens with original Doom3 on Windows as well (with and without OpenAL), maybe it's supposed to sound like that and the weapons just stutter every few shots or shot in bursts or something?

**Comment by hemebond** [comment]
I don't think it's an issue in the BFG edition of the game.

**Comment by thoughtartist** [comment]
No need to gaslight us over an obvious bug, DanielGibson. We know better.

**Comment by DanielGibson** [comment]
> No need to gaslight us over an obvious bug, DanielGibson.

Mind your manners, @thoughtartist. This is your first and only warning.

**Comment by DanielGibson** [comment]
The fundamental problem is that sound is only updated around 10 times per second, by the async timer in the async thread: https://github.com/dhewm/dhewm3/blob/master/neo/sound/snd_system.cpp#L680-L688 (`AsyncUpdate()` basically does the same but with more complicated code):
```c++
unsigned int dwCurrentBlock = (unsigned int)( inTime * 44.1f / MIXBUFFER_SAMPLES );
// inTime is current Time in milliseconds since the game was started
// MIXBUFFER_SAMPLES = 4096 (it's a constant defined somewhere)
// 44.1f / MIXBUFFER_SAMPLES == 0,010766602
// ...
if ( dwCurrentBlock < nextWriteBlock ) {
	return 0; // !!!
}
// ...
currentSoundWorld->MixLoop( sampleTime, numSpeakers, finalMixBuffer );
// ...
nextWriteBlock = dwCurrentBlock + 1;
```
so only if `inTime` has increased enough since last successful update to increase dwCurrentBlock, `currentSoundWorld->MixLoop(...);` is called - that is the case **roughly every 93 milliseconds (=> about 10 updates per second)**.
`MixLoop()` starts openal sounds and update ones already playing - for longer sounds streaming from .ogg files - and I think it also does sound effects or something, and calls into SIMD (SSE/Altivec/...) code. I think because of this streaming (decompressing chunks of data, `MIXBUFFER_SAMPLES` at a time) and the SIMD stuff (which needs correctly aligned buffers) this is only done every `MIXBUFFER_SAMPLES` samples. I'm not 100% sure which of these reasons (if any) are really relevant for the OpenAL backend, I assume with the software mixing code this was (even?) more important.

So imagine the gamecode tries to play a sound right after `MixLoop()` has been called - then can theoretically take up to 93 ms until `MixLoop()` actually tells OpenAL to play it!
And in practice it can even be a bit longer, because `AsyncUpdateWrite()` is called about every 16 milliseconds and if it's called one millisecond to early for `MixLoop()` to be called, the time `MixLoop()` gets called its 15 milliseconds late, which can cause delays of up to 108ms or so.. though those last 15-16ms don't make much of a difference at that point (but could be avoided with only small changes to the code).
And the actual delay drifts over time, due to the gamecode being updated every 16ms and `MixLoop()` (ideally) being updated every 92-94ms. For example, with the Machine Gun the delays were often like this:
```
delay: 80ms
delay: 76ms
delay: 39ms
delay: 17ms
delay: 13ms

delay: 90ms
delay: 52ms
delay: 32ms
delay: 28ms
delay: 8ms

delay: 66ms
delay: 62ms
delay: 41ms
delay: 20ms
delay: 15ms

delay: 75ms
... etc
```
(empty lines added to make  those blocks more visible)
So one shot with high delay, then 4 more shots, each a bit less delay, then it starts again with high delay - and keep in mind that the MP shoots 10x/second => one shot every 100ms!
This leads to the shots sounding like bursts and it can happen that two sounds are played so quickly after another that it sounds like one sound, which makes it sound like one is dropped (I didn't actually observe this, but if it somehow happens that the gamecode "starts" two shot sounds between `MixLoop()` calls, that the second actually cancels the first and it's *really* dropped).

As a side-note (mostly to myself) that async thread thing is pretty broken, it tries to only get the `AsyncTimer()` callback called about every 16ms, but in fact it's called every millisecond, calls `idCommonLocal::Async()` and that function will then make sure things (incl. `idSoundSystemLocal::AsyncUpdate()`) are only called every 16ms.
So as `idCommonLocal::Async()` is in fact called every millisecond, it could just call `idSoundSystemLocal::AsyncUpdate()` every time instead of every 16ms, so it'll indeed be called every 92-94ms. But as I said above, that doesn't fix the main issue..

Unfortunately, I'm not sure how to fix this issue, I'd have to find out if this "only update every 4096 samples" stuff is *really* needed and if it is, work around it somehow, and otherwise call `MixLoop()` more often.
All in all the OpenAL backend has been hacked ontop the old sound backend and thus carries restrictions from the (apparently already sub-optimal) old software mixing backends :-/
Not sure when/if I get around to this, just debugging to get these insights took a lot of time..

**Comment by DanielGibson** [comment]
I might have a fix (which assumes that the calls to software mixing functions were superfluous) - now sound is updated 60 times per second instead of 10 times per second which keeps delays below 16ms.
I tested it a bit an didn't notice any issues, but it definitely **needs thorough testing** for any new sound-related issues *anywhere* in the game before going into master.

Windows binaries: [dhewm3-oal-timing-fix.zip](https://github.com/dhewm/dhewm3/files/4713493/dhewm3-oal-timing-fix.zip)
Source code: https://github.com/dhewm/dhewm3/tree/openal-timing-fix

You can set `com_asyncSound 2` to get the old behavior for comparison (the meaning of com_asyncSounds values have changed a bit with this change), `com_asyncSound 1` (or 3) give you the new behavior.

Thanks in advance for testing!

**Comment by hemebond** [comment]
You got it 🎉. That is _so_ much better. It's even more obvious with the plasma gun.

**Comment by DanielGibson** [comment]
Great, I'm glad it works!
I just hope I didn't break anything else..
