### ISSUE TITLE
Shadow Bugs (r_useoptimizedshadows, r_useturboshadows)

### ISSUE THREAD

**Issue by shoober420** [dhewm/dhewm3#157]
There are numerous shadow bugs I've encountered on my playthrough of Doom 3. I'm not sure if you've noticed them or not. I can make a video and showcase all of them I found. Are you aware of the various shadow bugs? They appear even when "r_useturboshadow" and r_useoptimizedshadows" are set to 0.

**Comment by DanielGibson** [comment]
I'm not aware of any shadow bugs, a video would be appreciated.
Do you know if they also happened with the original Doom3 executables from id Software?

Of further interest would be your operating system and GPU (incl driver version)

**Comment by shoober420** [comment]
I found out what it is. It's my config. When setting the cvar "r_useoptimizedshadows" to 0, the shadow bugs are present. When enabling it, shadows appear normal. I set that cvar to 0 because it supposedly makes the shadows more detailed. I'll post a video of the shadows when this cvar is disabled tomorrow.

**Comment by shoober420** [comment]
This got alot more complicated. Depending on the shadow, the two cvars effect them different. Some bugs are fixed when enabling one or the other, depending on the shadow. I'll post some locations later today. I'm making the video now.

**Comment by shoober420** [comment]
When both shadow cvars are enabled (default settings), this fixes the bugs. Although disabling both those cvars should render higher quality shadows. I'm busy today, but will demonstrate some examples tomorrow.

**Comment by nbohr1more** [comment]
Neither of those are quality options. They are options to enable better hardware acceleration behavior.

r_useOptimizedShadows [0,1] - When set to 1, uses the dmap generated static shadow volumes, which provides optimal performance. (Precompiled)

r_useTurboShadow [0,1] - If set to 1, uses the infinite projection with W technique for dynamic shadows which improves performance without a noticeable drop in image quality.

That said, we saw shadow bugs due to compiler options in The Dark Mod. Are you using anything beyond vanilla IA64 in your compile?

**Comment by shoober420** [comment]
I'm just playing vanilla Doom 3. I'm not using the BFG edition either. I'm playing the original Doom 3.

The "r_useturboshadows" option does indeed sound like an option that renders lower quality shadows "without a noticable drop in image quality". I googled configs that are "ultra quality" and numerous ones all mentioned to disable these.

By there descriptions, they sound like performance optimization options for shadows when graphics cards weren't nearly as good as they are now.

**Comment by nbohr1more** [comment]
All the option does is set the shadow projection destination to an infinite vanishing point and stop
the geometry bounds where they intersect with the view port. In some ways this is actually better than capped shadows because the shadow bounds will extend beyond the volume geometry == no weird boundary.  In practice, it offers no visual difference to capped shadows because the engine does not shade outside the light bounding box so it is simply wasteful. It performs better because calculating the cap is more expensive than drawing the extra shadow tris even with this wasteful overdraw work. There could be some pathological case where shadow overdraw is so insane that capping is cheaper but it's never been seen in practice.

**Comment by shoober420** [comment]
So I should just leave both those cvars set to "1"?

**Comment by nbohr1more** [comment]
Yes.

The values should probably be hard-coded to 1 and the cvars should be dropped but that's not my call.

**Comment by shoober420** [comment]
OK, just for reference, I'll still do a video and show the behavior of the shadows are effected by using a value of 0.

**Comment by shoober420** [comment]
I decided to just leave this be. There's no use making a video if the options should be enabled. I'll just close this. Thank you for all the information.
