### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by Askmewho** [dhewm/dhewm3#197]
/usr/bin/ld: no se puede abrir el fichero de salida dhewm3: Es un directorio
collect2: error: ld returned 1 exit status
CMakeFiles/dhewm3.dir/build.make:4133: fallo en las instrucciones para el objetivo 'dhewm3'
make[2]: *** [dhewm3] Error 1
CMakeFiles/Makefile2:104: fallo en las instrucciones para el objetivo 'CMakeFiles/dhewm3.dir/all'
make[1]: *** [CMakeFiles/dhewm3.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....

**Comment by RalfVB** [comment]
Building dhewm3 is actually reasonably straightforward, especially on Linux.
Just create a 'build' dir next to 'neo': `mkdir build`
Change to it: `cd build`
Then run cmake: `cmake ../neo`

If this step finished without errors, you should be able to build dhewm3 by typing `make`.
If any errors occurred, it's most likely because you do not have all the required libraries installed.
