### ISSUE TITLE
Mod porting questions

### ISSUE THREAD

**Issue by revility** [dhewm/dhewm3#198]
I am looking into porting our ruiner and hardqore 2 mods to dhewm 3.  there are about a dozen modified and new files for each one.  Keep in mind that I have not used visual studio almost 8 years nor did I do the coding for the final year of development for them :p I've had no issues compiling and running dhewm 3 itself.

I figured the best way to port the code over was to do a code compare.  It mostly seems pretty straight forward with a majority of the code changes having been commented.
I noticed the precompile stuff is gone.  What is the best way for to find out what to include in the new files we added?

The ruiner mod contains source hooking.  I believe this was added by denton for HDR.  We use a version of his mod as a base.  He modified it a bit for us for hdr and bloom.  So we are not using the same version that is in his source release.  Is this something I'll be able to keep in the mod?

Any help would be greatly appreciated.  I'm mostly looking to just getting the mods ported and some small changes for the current build of ruiner i'm working on.  Afterwards the codes would released to the public like we have done in the past.

**Comment by DanielGibson** [comment]
Hi revility, thanks for your interest in porting your mods to dhewm3!

I once started a thing for mod support: https://github.com/DanielGibson/dhewm3-mods and https://github.com/DanielGibson/dhewm3-base-mods
And it doesn't work with current dhewm3 git master code, but needs some modifications to the build system: https://github.com/DanielGibson/dhewm3/tree/new-mod-support

I'm thinking about trying to make this easier, maybe I can create a SDK with dhewm3 code that contains everything to build a mod (so mods can be built without messing around with git submodules and such).
Either way, the easiest way to port the mod to dhewm3 is to make a [diff](https://en.wikipedia.org/wiki/Diff) between your mod code and the original Doom3 SDK, and apply that diff (patch) to the dhewm3-base-mods master code - that's what I did with Classic Doom III and Dentonmod.

One possible problem is that the mod source would need to be (re)licensed under GPLv3, because the SDK license is incompatible with the GPLv3 (as used by the Doom3 GPL release and thus by dhewm3). The Classic Doom III and Dentonmod authors agreeds to this, that's why they're in the aforementioned base mods repo (each in their own branch).

If the GPL is no problem for you, I can help you with porting your mods if you like, I just need to source :)

**Comment by revility** [comment]
Thanks for the reply!

I have no issues with the code going gpl. I just have no clue on how to do it.  We released the source code years ago and can be found on the mod db:

https://www.moddb.com/mods/ruiner/downloads/ruiner-hardqore-2-source-codes

I updated the readme this year with what I believe is a full list of any hands that were in the code back then... it's been around 8 years since it was released.

I have done a few changes to the ruiner code this month in 2 files.  Nothing crazy and easy to replicate.

Help porting would really be appreciated.  I'm working on a hefty update for Ruiner and was going to tackle this after that... but if the port happens before the update, then that would be really awesome.

**Comment by DanielGibson** [comment]
I'm currently evaluating if it's reasonably easy to create a dhewm3 "SDK" that contains the same source files as the original SDK, but taken from dhewm3 instead, so they include all the changes and game dlls built with that should work with dhewm3 then.
If that turns out to be feasible, that should be a good base to port Doom3 mods to - if not my older approach (with the repos linked above) should still be okayish.

When that is done (hopefully next weekend or so, if this turns out to be really easy even sooner) I'll try to port your mods - when did you want to release the for Ruiner?

**Comment by revility** [comment]
I'm currently shooting for by the end of next month or early October for the next release so there is plenty of time. 

A ported HardQore release would be any time.  Having HQ2 up would open the door for people to create 2.5 side scrollers.  We implanted more features than used in the mod... enough for a basic metroid clone.  There are no known bugs in the code.  I don't plan to update the mod until wrapping a few more updates on Ruiner.

**Comment by DanielGibson** [comment]
Sounds great!

Can you send me an E-Mail so we have a more direct communication channel?
(I think everyone who "watches" this repository gets E-Mail notifications for all these issues and comments..)
My E-Mail is metalcaedes@gmail.com
Thanks!

**Comment by RalfVB** [comment]
Speaking of mods, I'm working on one myself. One aspect of Doom 3 modding that makes the process not as nice as it could be is the general shape of Doom 3's data, which meets the bare requirements to qualify for a commercial release. It's a mess, and I'm being kind. Nearly half of all declared materials do not work, declarations are all over the place, many files are full of unusable leftover material and aren't properly formatted. These things do not matter to someone who just wants to play the game, but is very hard to overlook for OCD-ridden modders like me.

So I've basically been doing some work re-packing and re-structing Doom 3's data, cleaning out all the redundant stuff, and just basically stripping it to the minimum required to play Doom 3. I'm afraid I'm not going to stop there, replacing the original low-res textures with the Wulfen ones, and possibly even merge all the content of Resurrection of Evil as well, providing a superior and much friendlier base for modders to work with.

The frustrating thing obviously is that I won't be able to share it with my fellow modders :s

**Comment by revility** [comment]
I don't know if it's around anymore, but there used to be clean material packs floating around for mappers to use.  All the broken materials were removed in it.
I have a new hell texture pack on the mod db.  In it you'll find cloned materials of the working hell textures separated from the default ones to keep it more organized for mapping.  All the new textures in the pack blend in well with stock doom3 hell stuff and resolution.
