### ISSUE TITLE
graphics improvement

### ISSUE THREAD

**Issue by ManoaNosea** [dhewm/dhewm3#205]
I've read about all the modifications of the project like multi-platform, openAL, 64-bit and such improvements, this is nice, but what about the improvements to the graphics ? shaders ? an alternative to sikkmod so that it would be possible to run mods from their data and not require their gamex86.dll's ?
right now I am developing one of the biggest doom 3 modifications and I would prefer to run on open surce doom 3 project, but the graphics is missing :x are there no additional programmers that can add many graphics-oriented improvements to doom 3 ?

**Comment by RalfVB** [comment]
Allow me to chime in, as a fellow modder.

In the case of Sikkmod, I understood the original developer isn't around anymore to give us permission to implement his code. I find it hard to believe doing so anyway will cause any problems because the source code was available, just not explicitly published under the GPL - what problem could the developer possibly have with using his work - properly credited - and expose it to a wider audience, instead of letting it wither and die?...

The capability for better graphics is always nice, but from my perspective not the highest priority. What dhewm3 needs is a larger community. Just look at Doom or Half-Life, which have thriving communities, which attracts talented developers who produce splendid content, growing the community further.

The Doom 3 community is barely nonexistent. There's some people here and there producing interesting stuff, but unless dhewm3 development picks up and aims to become the de facto platform to run Doom 3 content on, I'm afraid it'll stay niche, which is a shame as the engine is an amazing piece of technology with the potential to create fantastic gaming experiences.

I believe I'm doing my part by completely reorganizing and restructuring the game data, which simplifies mapping and modding considerably, even though distributing that data is going to be legally troublesome.

Lowering the barrier to entry is the key to get dhewm3 the community it deserves. Direct support for file formats such as PNG, FLAC and 7z would be good, even though Daniel isn't in favor of it.

**Comment by revility** [comment]
I’ll chime in as well.  

When adding this kind of stuff it gets murky.  Compatibility & performance becomes a big issue with shaders.  It’s also a different kind of coding.  Fhdoom has a more modern shader system, & some new additions.  But no one has yet to add in stuff like hdr.  For that I would look at the dark mod as they are on glsl shaders.  Performance & compatibility is what one needs to take into consideration when it comes to new effects.  So many things in sikkmod drop performance too much. 

We have hdr, bloom & improved ambient lights for ruiner & hardqore...  both sources are available on the dhewm 3 sdk.  I still get issues from users with ati cards every so often about it.  But nothing from nvidia users.  Luckily they can be turned off.  Your free to use them.  You can also find hdr & bloom in the dhewm 3 denton mod.  
Denton mod is probably the best base to start a mod with just because of all the little useful things it adds & improves.  You might not know it at first,  but will on e you go back to vanilla after using it.  

To improve the community,  we need more mods beyond tech demos.  There needs to be a repository for little stuff similar to realm667 to get things going for a modder & also learn from.  If you look through that place most of the stuff is very simple,  but also very useful to get the ball rolling.

**Comment by ManoaNosea** [comment]
denton is nice :)
I will look into building on it for open surce version....but my direction for doom 3 is for cooperative against monsters :x not realy one against the other just dethmatch...with friendly fire and realistic interactions, I guess there are no mods that go in cooperative direction for dhewm ?

it the true sikkmod have many problems include performance, it was never realy finished and some things are just post (HDR and bloom done in 2D not 3D, ambient occlusion done post: smoke effects are on-top of the AO :x) there are also some problems with parallax occlusion: strange looking at some angles :x

so need people, I tell you this: almost all doom 3 dedicateds are almost 100% of the time 0/0 :x
this suckx :x I like to play MCS coop but it always empty :x

FLAC and 7z is good, I +1 :) ... but PNG I'm not sure does he have dedicated alpha image like tga ?

from what I understand you guys big problem is no people and that graphics will not help with more people :x

**Comment by DanielGibson** [comment]
No one needs FLAC in games, ogg sounds just as good, esp. at higher bitrates, and is significantly smaller.
There's not much point in PNG, it doesn't compress that much better than putting a .tga in a .zip - and usually .dds textures are preferable anyway, because they load much faster.
.7z is not a great idea either - it might compress a bit more than .zip, but extracting it (=> reading from it) is much slower than ZIP.

I don't think supporting any of these filetypes would significantly make modding easier or better. What difference does it make if you convert your textures to png or tga? Or your sounds to ogg or flac? Or if you pack things in .7z or .zip (.pk4)?

Yes, Sikkmod had performance problems (which I guess are at least partly to blame on the restrictions imposed by non-GPL Doom3 back then). And it has a license problem that I'm not gonna ignore.

As @revility said, look at Dentonmod and/or Ruiner for graphical improvements.
Additionally, if you want a more modern renderer (and the ability to use GLSL shaders instead of those arcane ARB assembly shaders), https://github.com/eXistence/fhDOOM/ might be interesting - or even https://github.com/RobertBeckebans/RBDOOM-3-BFG/ or https://github.com/OpenTechEngine/OpenTechBFG (based on RBDoom3BFG).

The Doom3 engine is almost 15 years old now - it's not meant to look modern and it doesn't use multicore CPUs very well. Using it (or dhewm3) for Doom3 mods makes sense, using it for games in the graphical style of that generation (or *a bit* better) might make still be ok, but if you want your game to look modern, you should take a look at more modern engines, like https://godotengine.org/ or https://xenko.com/.
Or at least something based on D3BFG, which is multi-threaded and has a modern renderer (apparently they took parts from Rage); however, tool support for that is worse than for Vanilla Doom3 (though dhewm3 doesn't have the original editors either).

The goal of dhewm3 is to let people play Doom3 (and doom3 mods, if feasible) on modern hardware - not being a modern general purpose engine.

**Comment by nbohr1more** [comment]
The Dark Mod also has graphic improvements...  ;)

**Comment by ManoaNosea** [comment]
no I was not looking to choose an engine for generally making a game, I am specifically looking for doom 3, and only doom 3 (not even BFG). fhDOOM looks very good, I like it alote thanks, but for this to work at all (and it could, either with fhDOOM or with this project - both can be modded to create graphics that is good, mybe fhDOOM better) there is still one thing that both projects don't have: a coop mod :x

there are 3 coop mods for doom 3 in the world: open coop, last man standing 4 coop and mars city security coop. but because of requirement to compile and/or modify gamex86.dll to run specifically on a given engine - none of them can work on any of the open surce engines :x so I am stucked :x

**Comment by ManoaNosea** [comment]
I have this link: http://idtechforums.fuzzylogicinc.com/index.php?PHPSESSID=10123ii31saqhoi46ng4esqsc7&topic=404.45
it a fhDOOM thread, the author of MCS (8devilz) is talking there. why he didn't make a version of the DLL for either fhDOOM or for your project is because the code cannot be open surce ? what about making a coop DLL that is not based on open coop at all ?

**Comment by DanielGibson** [comment]
Oh, it would be absolutely awesome if you implemented a new coop mod that's not based on opencoop!

**Comment by ManoaNosea** [comment]
if there no way to make the engines either fhDOOM or your project compatible with the DLL's ?

**Comment by ManoaNosea** [comment]
> Oh, it would be absolutely awesome if you implemented a new coop mod that's not based on opencoop!

programming a cooperative mode into the engine is very hard ?

**Comment by DanielGibson** [comment]
> programming a cooperative mode into the engine is very hard ?

Don't know, I've never tried, but I think that the developers of opencoop and the other mods spent lots of time to make it work.

But the best way to find out is to try it yourself :)

**Comment by ManoaNosea** [comment]
im affraid programming is not my department :x I can make some modifications to graphics in mods but this is work for real programmers, I hoped that with source code of doom 3 it could make it much easier, since the coop mod developers did it when the source was closed :x

**Comment by DanielGibson** [comment]
No, I think it would be (almost?) completely done in the code for  the game dll, just like opencoop did.

**Comment by ManoaNosea** [comment]
if you want it to be a mod-side option, I was thinking along the lines of source code making it easy to code a non-mod side coop mode into doom 3 :)

**Comment by revility** [comment]
when it comes to tga's... the only thing I ever wanted to see was 32 bit alpha support for better decals, transparency and open the door for doing some good hair & fur.  But idk what that would take or any performance hit.  Thats one of the few little things I can think of vanilla d3 would benefit from image wise.

**Comment by RalfVB** [comment]
And sound-wise, support for 44Khz audio. If I try to play any audio at that rate in dhewm3, it's played at half rate.

All of your arguments against the file formats I proposed are valid Daniel, but you are overlooking 'ease of use'. Having to convert all media down to lossy formats is extra work, I miss being able to throw any old image in there to see if it works as a texture like I can with gzdoom, or any old audio file.

I understand you're not keen on putting in the work for implementing support yourself - but would you accept a pr with these features?

**Comment by DanielGibson** [comment]
32bit alpha? Does that mean that just the alpha channel has 32bit? Is that a thing?
(I know there are HDR image formats with 16bit per channel, but 32?)

44khz audio sounds sane (*however, see below*); I'm not very familiar with Doom3's audio system, does this mean it only supports 22khz?

> All of your arguments against the file formats I proposed are valid Daniel, but you are overlooking 'ease of use'. Having to convert all media down to lossy formats is extra work

Don't you have to write a material for the texture anyway? Isn't that much more work than converting to TGA?

> I understand you're not keen on putting in the work for implementing support yourself - but would you accept a pr with these features?

*Maybe*, not sure - certainly depends on the feature. For example, 7z support just doesn't make any sense at all to me, PNG makes a bit more sense at least (though I dislike it for being slow to decode and loading Doom3 levels *already* takes quite long).
One thing is that I'd certainly like to avoid further external dependencies (libraries); however that problem could be avoided by using libs that can easily be included, ideally header-only libs like stb_image.h etc
Another issue is that this would make content created for dhewm3 incompatible with original Doom3 and other source ports. This could also cause trouble with the tools: dhewm3 supporting PNG textures (for example) is pretty useless, if your level editor does not support it - and I can imagine that many still like using D3Radiant with the original Windows binaries?

**Comment by revility** [comment]
Nevermind my terminology is not correct for the tga’s.  24 & 32 is supported, duh me. I will try to find out exactly what i mean.

**Comment by raynorpat** [comment]
> 44khz audio sounds sane (_however, see below_); I'm not very familiar with Doom3's audio system, does this mean it only supports 22khz?

@DanielGibson and @RalfVB If you take a quick peek in snd_cache.cpp - each idSoundSample is set to 44khz by default, unless the actual wav file is not a 44khz sample. Ogg files are always output at 44khz.

**Comment by RalfVB** [comment]
That's good to know.

OGG is decent audio format, but not optimal. I can get the decoder to crash in certain cases, and having to disable the shaking feature because it doesn't work with OGG is stupid.

Also, you are the guy who did Rivensin, right? I'm not too interested in 3rd person hack & slash games, but I have to say I'm impressed with what you achieved on a technical level. Very nicely done.

Would you mind if I would take the female character model and have her act as an NPC in my mod? With full credits and acknowledgements, of course.

**Comment by revility** [comment]
Go for it!  You’ll find multiple unused player models inside both rivensin & hardqore.

**Comment by DanielGibson** [comment]
I guess there's no more open questions that would make sense to discuss here?
