### ISSUE TITLE
Low framerate on powerful rig

### ISSUE THREAD

**Issue by Mechanical-sanity** [dhewm/dhewm3#237]
I have a rig that is powerful enough to run doom 2016 at high settings, and I can't even run this with 20. Is there a reason why the framerate is so low for me? Is there a way for me to increase fps? I'm trying to run the game at max settings and at 1080p.  Its frustrating, because I would love to play doom 3 with this engine

**Comment by DanielGibson** [comment]
dhewm3 usually runs smoothly on halfway-modern hardware - but you give me zero information here, so how should I know what's going wrong on your system?! :-P

What CPU and what  GPU are you using? What operating system? Which version of dhewm3?

**Comment by RalfVB** [comment]
I ran dhewm3 for years on a modest i5 with Intel Haswell graphics, with great performance (at 1280x720).
You probably have a configuration problem somewhere.

**Comment by DanielGibson** [comment]
> I ran dhewm3 for years on a modest i5 with Intel Haswell graphics, with great performance (at 1280x720).
> You probably have a configuration problem somewhere.

Yeah, I guess so too. I wouldn't mind at least trying to help @Mechanical-sanity figure it out, but for that I'd need the information I asked for (and probably more from follow-up questions) :-)

**Comment by DanielGibson** [comment]
So does the problem still persist?
If not, can you share how you fixed it in case someone else runs into the same problem?

**Comment by darkcharmander** [comment]
I would like to re-open this issue, since I've noticed the same thing.

The game is incredibly heavy on the GPU. On ultra-graphics @ 1440p, with AA at 16, my GPU cannot even sustain 60FPS. With AA at 8, I still get occasional dips below 60FPS. (For some reason my FPS is stuck to 63, but that's another matter)

GPU load is always 80-90%. Same story for both of my GPUs. (AMD Renoir, Nvidia GTX 1650 Ti). Not including the CPU models, because both CPUs are overpowered anyways, and the load on them is not high.

On my other rig with the 1070 Ti, the problem does not exist. GPU load is about 30-40% there. So why is this a problem? Well, if you compare it to the fact that my rig can run Skyrim on ultra graphics @ 1440p at 75FPS nearly all the time, it becomes clear that this game is much heavier than it is supposed to be. (Skyrim is a much more graphics intense game, obviously)

Perhaps it's just because the engine is old and doesn't run too well on modern systems or something.

**Comment by DanielGibson** [comment]
this is not quite the same thing - there's a difference between not quite sustaining 60FPS @1440p, AA16 and ultra settings, and only making 20fps @1080p..

FPS being stuck to around 60 is normal, Doom3 doesn't support more than 60fps.

"the load on the CPUs is not high" - dhewm3 only really uses one core, so even if the overall load is not high, if one core is at full load that's enough to slow down the game - but I guess that also isn't the case..

yes, modern systems, esp. GPUs and their drivers, are obviously not optimized for Doom3 anymore

**Comment by darkcharmander** [comment]
>this is not quite the same thing - there's a difference between not quite sustaining 60FPS @1440p, AA16 and ultra settings, and only making 20fps @1080p..

I know. I am not the guy who has created this issue, I have a very different computer. But the same principle applies, because I see where he is coming from, given that the game is also very demanding from my system. Smokin' Guns for example, uses the Quake III engine, and I always have 125+FPS there, even on super-duper graphics settings. I just think that it's strange that such an old game is so demanding.

I cannot try it in vanilla Doom 3, because it doesn't support 1440p. Trying to force 1440p anyways, causes the Nvidia driver to trip, and then trigger a BSOD, which I just had... thnx M$.

>FPS being stuck to around 60 is normal, Doom3 doesn't support more than 60fps.

I've read that in another issue yeah. I meant by 63FPS that on one of my systems, the FPS is 63 instead of 60, which is odd. But then, the game takes like 10+ seconds on my system to start, while on my other system it starts up instantly. Cannot quite explain what's going on here. Both systems are ridiculously fast, so I don't have a clue. Except for driver issues, that is.

I don't mind it a lot that the game is this level of demanding, since I can still run it pretty well. I wanted to say it regardless, because it's just a bit odd.

**Comment by DanielGibson** [comment]
Smoking Guns/Quake3 is one generation older, which was a lot on those days.

Doesn't original Doom3 also have r_customWidth/Height (which is used if r_mode = -1)?

Yeah, I think it'll be more like 62.5fps, because each frame is exactly 16ms (instead of 16.666fps as it should be at 60Hz), and 1sec == 1000msec and 1000/16 = 62.5

It really shouldn't take 10+ seconds to start; usually this kind of issue can be blamed on antivirus software that pauses the whole process until its done scanning it (and possible its game data)

**Comment by darkcharmander** [comment]
>Smoking Guns/Quake3 is one generation older, which was a lot on those days.

Ah. I thought that Quake 3 was the newest one.

>Doesn't original Doom3 also have r_customWidth/Height (which is used if r_mode = -1)?

It does. I've tried to force the resolution via r_mode 23. That caused a BSOD. Trying it via r_mode -1 with the width and height set accordingly, does work! The GPU load there is like 97% all the time, so I then can confirm that the high-load of the game, is **not** caused by your port! The only way to test such a thing was to try and run vanilla Doom 3 with the exact same graphics settings.

>Yeah, I think it'll be more like 62.5fps, because each frame is exactly 16ms (instead of 16.666fps as it should be at 60Hz), and 1sec = 1000msec and 1000/16 = 62.5

For sure. I often see it flashing to 62FPS for a little bit, so it must be indeed 62.5. My other system has 60FPS though, which is strange! I think that the driver there more strictly adheres to vsync. (It was a remote connection, and the FPS limit was 60, so that is probably it)

>It really shouldn't take 10+ seconds to start; usually this kind of issue can be blamed on antivirus software that pauses the whole process until its done scanning it (and possible its game data)

Wow, this is insane. I only have Windows Defender, which I keep enabled, despite me having the same stance against AV software as you. Windows Defender definitely causes this: after disabling it, the game starts up instantly. My other system has Windows Defender enabled also, so I don't know why that one doesn't act so stupid. Probably because MS has messed up Windows Defender in some way. I expected Windows Defender to not be so stupid (I know the AV software often does this), and that is why I didn't even check if the cause of the problem was AV software.

Thanks for your answers. I think you can close this issue, since I've now confirmed that your open-source port of Doom 3 does  **not** cause a performance penalty.

**Comment by DanielGibson** [comment]
yeah, r_mode 23 wouldn't work, it's a mode I added in dhewm3, the original has fewer modes.
good to know the issue also affects original Doom3
I'm not against investigating the performance issues and trying to fix them (I agree that one would expect Doom3 to run a lot faster on modern machines), I just don't have time for it and I'm not very experienced in graphics programming

functioning vsync should enforce exactly 60fps

windows defender AFAIK is the least crappy AV, but it's still weird - at some point we even had the situation that on two computers with the same version of windows and windows defender and its signatures, one detected dhewm3 (or was it YQ2?) as malware and the other didn't..
you could configure it to ignore the dhewm3/doom3 install directory, that way you don't have to disable it entirely but dhewm3 should start quickly again

**Comment by darkcharmander** [comment]
>yeah, r_mode 23 wouldn't work, it's a mode I added in dhewm3, the original has fewer modes.

Yup, I also knew this, and expected it to 'not' work, but I definitely did not expect a BSOD!

>I'm not against investigating the performance issues and trying to fix them

I agree. Graphics programming isn't my forte either. But now everything is fine, since there is no performance penalty! I think you should also not try to improve the performance now.

>functioning vsync should enforce exactly 60fps

Absolutely. Well, 75FPS in my case. VSync nowadays is a bit fucked. I mean, the nvidia driver controls half of it, but sometimes games still refuse to ignore VSync after turning on off in the driver software (And even after turning it off in the game). When you turn off VSync in Skyrim and in the nvidia driver panel, the game will run at e.g. over 150FPS, but the physics totally get fucked up (It becomes pretty much unplayable). For a game from 2004, I can still understand it a bit. For a game from 2011, it's just unacceptable.

>windows defender AFAIK is the least crappy AV, but it's still weird...

That's strange! I have ESET at my work, and when we compile our code, the compilation takes MUCH longer if ESET is not configured to ignore the source directory. So annoying!!!

>you could configure it to ignore the dhewm3/doom3 install directory, that way you don't have to disable it entirely but dhewm3 should start quickly again

I was just at the point of doing that, but after turning off 'Cloud-delivered protection' in the Defender settings, the problem went away suddenly. Magic!

**Comment by fabianoengler** [comment]
Sorry to revive this, but I had a similar issue and after a lot of frustration, I was able to finally pinpoint what was causing it, so I'm just posting in case it can help other that land here from google as myself.

I have GTX 3080 Ti with 64 GB ram with i9 CPU, can run everything i tried with all maxed in 4k, including D2016 and Ethernal, so you can imagine my frustration when, although D3 started at 60FPS, during battles it went to 20-30 and lagged a lot, making it very bad to play at the most crucial moments.

After googling around I spent a lot of time trying to fiddle with a lot of settings, which takes some time, because most video/rendering settings requires you to restart dhewm3 to take effect and, in my case, since it was the battles the affected part, i managed to do a quicksave just before a battle with a few monsters so I could test the fps, but the first time you load from save takes a lot of time.

Anyway, I was finally able to pinpoint the issue, it was the antialising settings. To change it, open console (with ` key), type `seta r_multiSamples 0`, this will disable AA, which fixed it for me (need to restart the game every time you changed this). After that, you can try upping it incrementally to 2, 4, 8, 16. On my rig I can go up to 8x without FPS issues.

At 3840x2160 res with 8x AA on was able to run the game very smoothly at vsynced 60 FPS without any issues at all, including using the mod [D3HDP v2.0 (DooM 3 Essential HD Pack v2.0)](https://www.moddb.com/mods/d3hdp-doom-3-essential-hd-pack), a high definition texture pack that makes this game look absolutely amazing at hidef.

As a curiosity, I notice the Imp caused a lot more fps issues than other monster like zombie, pinky, etc. I supposed the lightning calculations for the fireball and all the shadows are really heavy and that part with 16x AA made rig go on its knees.

**Comment by nbohr1more** [comment]
Using in-game AA is always gonna be a problem for the native Doom 3 engine design. The engine is fillrate limited due to the stencil shadow design and AA just multiplies the fillrate problem ( as does resolution ). 

If you want AA without much of a hit, consider forcing FXAA in your drivers ( sorry AMD owners, not sure what options you have these days ). 

If you want a Doom 3 version that is less affected by AA performance problems consider use Doom 3 BFG or ( even better ) it's open source variant RBDoom3BFG. 

Unless someone wants to offer a patch to either reduce fillrate somehow ( shadow maps, forward plus rendering, etc ) or add alternate AA \ upscale options ( FXAA, MLAA, DLSS, XeSS, FSR, etc)...

**Comment by DanielGibson** [comment]
TBH, 8x MSAA isn't that bad, probably looks better than FXAA?
Sucks that 16x doesn't work that well, but I can't do anything about it, and many cards/drivers don't even support more than 8x
