### ISSUE TITLE
Crash on loading map monorail

### ISSUE THREAD

**Issue by nzbtuxnews** [dhewm/dhewm3#268]
Game was working perfectly until loading the map monorail.  Now at the end of the loading bar, the game crashes to desktop with the following error:

`dhewm3: /build/dhewm3-efsAPQ/dhewm3-1.4.1+git20171102+dfsg/neo/game/physics/Clip.cpp:968: bool TestHugeTranslation(trace_t&, const idClipModel*, const idVec3&, const idVec3&, const idMat3&): Assertion '0' failed.
Aborted (core dumped)`

Running on linux mint, installed with apt-get

Game version: 1.4.1.1304 linux-x86_64 Nov 28 2017 19:21:13 using SDL v2.0.8

Attached is the output of the game launch and map loading in terminal.
[output.txt](https://github.com/dhewm/dhewm3/files/4024594/output.txt)

**Comment by DanielGibson** [comment]
Hi, can you try if this is fixed in dhewm3 1.5.0 or newer?
There's 64bit Linux binaries at https://github.com/dhewm/dhewm3/releases/tag/1.5.0
just unpack them and (in a terminal in that directory) run `./dhewm3 +set fs_basepath /path/to/your/doom3` to start it and tell it where to find the game data.

**Comment by nzbtuxnews** [comment]
1.5.0 seems to work perfectly!  I am not sure how to cleanly update the package on Mint and how to warn the package maintainers but I will try to...

Thanks Daniel!  and Great Work on this engine!

**Comment by DanielGibson** [comment]
I'm glad you like it!
Ubuntu 19.04 and newer ship dhewm3 1.5.0, but I guess it'll take a while until that ends up in Mint (probably in their next release)..
I guess you could report the bug at Ubuntu, but I doubt they wanna update the package in a LTS distro to a new major version

In the end, I'd always suggest getting source ports directly from the project instead of distribution repos, especially if those distros aren't bleeding edge and thus ship old releases.
dhewm3 even offers Linux binaries (though they're a bit outdated now), but usually on Linux source ports aren't that hard to compile yourself
