### ISSUE TITLE
Add an Android build please?

### ISSUE THREAD

**Issue by Destroyer5150** [dhewm/dhewm3#269]
Android has bfg edition but no touch screen support or mod support. Also I'm running diii4A almost perfectly on my galaxy S9 but it'll only run Doom 3 without resurrection of evil or mod support and it's old (2013) and dead and like I said "almost perfect" no fps drops at all. Xash3d Android (Half Life) has a decent touch screen control scheme that would work well for Doom 3. Thank you for your work

**Comment by Destroyer5150** [comment]
Here's what I've been using to play doom 3. The source code is inside the apk just extract it like a zip. 
https://diii4a.en.uptodown.com/android

**Comment by RinMaru** [comment]
Id be glad for a Vulkan Version

**Comment by Destroyer5150** [comment]
And Beloko ported your engine to android! (    https://play.google.com/store/apps/details?id=com.opentouchgaming.deltatouch ) Can you please create your OWN android build?

**Comment by DanielGibson** [comment]
no.

**Comment by tunbridgep** [comment]
> And Beloko ported your engine to android! ( https://play.google.com/store/apps/details?id=com.opentouchgaming.deltatouch ) Can you please create your OWN android build?

Is this even legal?

From my understanding, dhewm3 is gpl3. Delta Touch is a closed-source, proprietary application. Even if it's just calling up the android version of dhewm3, wouldn't that version still have to be GPL3 source available?

If so, where's the dhewm3 port?

I want to play Doom 3 on Android without paying some schmuck to play games I already own

**Comment by DanielGibson** [comment]
I think the GPL only requires you to give the source to your users, which in this case are paying customers (and then those users are allowed to redistribute the source for free under GPL), i.e. you are *not* required to make your source openly available.

However, isn't https://github.com/emileb/d3es-multithread the source of "Deltatouch"?

**Comment by tunbridgep** [comment]
GPL in theory means you only have to give the source to your customers, but the fact that nobody has made it available makes me think nobody has actually ever had access to it, including paying customers.

I dunno, Delta Touch rubs me the wrong way, because I kind of feel like it's taking the hard work done by the community, slapping an android control scheme on top of it, and then selling it, which seems kind of dickish to me.

But hey, I now have a free and open android version of Doom 3 to look at thanks to suggestions in this thread, so thanks for that.

**Comment by DanielGibson** [comment]
> GPL in theory means you only have to give the source to your customers, but the fact that nobody has made it available makes me think nobody has actually ever had access to it, including paying customers.

No idea, but as long as paying customers get it when they ask for it, that's ok. (In fact, they could even ask for money for the "work" involved with that, I think this rule goes back to the pre-internet days when GPL software was shared by sending around tapes)

> I guess I am biased. Delta Touch just rubs me the wrong way, because I kind of feel like it's taking the years of hard work done by the Doom 2 and Doom 3 source port communities, slapping an android control scheme on top of it, and then selling it, which seems kind of dickish to me.

Don't know, it's not that expensive and I personally would neither want to deal with implementing a mobile control scheme nor with building and packaging for Android.
Also, dhewm3 as it is wouldn't work on Android, because most Android devices only support OpenGL ES, not "normal"/"desktop" GL that's used by Doom3 (and certainly not this legacy GL with ARB shaders), so there was some more work to be done than "just adding an Android control scheme" (though they likely took the OpenGL ES renderer from the old abandoned Dante source port).

**Comment by tunbridgep** [comment]
I just think we're all better off if Android versions of doom were handled by community effort, rather than some guy doing all the work and not helping anyone else.

But it's mainly gzdoom that annoys me. That's a source port with a long history of community involvement, and the main reason people use Delta Touch over the other mobile versions of doom is for playing GZDoom mods. Literally the only market Delta Touch has is one that relies on it leveraging itself on community work.

But I will stop preaching. I will check out that openGL ES version of Doom 3. I still think it's worth the community getting it the best it can be on Android, but I understand that's out of scope for this project, which is fair enough.

**Comment by DanielGibson** [comment]
For GZDoom on Android, https://github.com/emileb/gzdoom might be worth a try

(but IDK, I don't even have a smartphone)
