### ISSUE TITLE
Game looks weird Debian Sid dhewm3 1.5.1

### ISSUE THREAD

**Issue by EstebanMonge** [dhewm/dhewm3#306]
I have one AMD Radeon Raven with Athlon Silver CPU, when game starts looks weird.

![shot-2020-07-30_01-01-50](https://user-images.githubusercontent.com/1070783/88891777-f4f8cb00-d200-11ea-8060-0fda05473e03.jpg)

**Comment by DanielGibson** [comment]
I assume this is a driver/mesa/whatever bug, but I haven't done any further testing myself yet.

Have you tested any other OpenGL games?
(though even if others work, Doom3 is kinda particular because it uses ARB assembly shaders instead of GLSL, but that might narrow the problem down a bit)

**Comment by EstebanMonge** [comment]
Hi, I don't play a lot, usually only doom saga jjj, but I installed SuperTuxKart and SuperTux, both are playable and ran well.

**Comment by DanielGibson** [comment]
Ok; I'll ask a friend who runs Arch Linux (=> also pretty bleeding edge) with a Radeon RX580 to test the dhewm3 binary from debian sid, just in case there's something wrong with them.

There never have been big changes to the renderer in dhewm3, it should be about the same it was in Doom3 15 years ago.
One relatively recent change to the renderer was the reintroduction of "Carmack's Reverse" and the usage of `glStencilOpSeparate` in that code. I don't think this should break the menu (but only affect shadows), but you could try disabling those changes by starting dhewm3 with `./dhewm3 +set r_useCarmacksReverse 0 +set r_useStencilOpSeparate 0`.

If that doesn't help you could try building dhewm3 from latest git yourself, see https://github.com/dhewm/dhewm3#compiling (don't worry, it's not too hard) - or try the (very recent) dhewm3 Linux amd64/x86_64 binaries from https://github.com/dhewm/dhewm3/releases/tag/1.5.1_RC2

If that still doesn't help you could try out a native build of https://github.com/gabrielcuvillier/d3wasm/
(if you build it the same way you build dhewm3, you should get a native binary instead of the emscripten thing for the browser, see https://github.com/gabrielcuvillier/d3wasm/blob/master/BUILD.md#6-enjoy)
It's based on dhewm3, but has replaced the OpenGL 1.4 + ARB shaders renderer with OpenGL ES2.0 (and GLSL shaders) - if that works then probably the AMD driver (or mesa or whatever) in the sid packages has broken [OpenGL ARB shaders](https://en.wikipedia.org/wiki/ARB_assembly_language).

**Comment by DanielGibson** [comment]
Oh, forgot to mention, if you built dhewm3 yourself, you can just run it with `./dhewm3 +set fs_basepath /path/to/your/doom3/` to tell it where to find the game data, so you don't need to copy anything around.

**Comment by EstebanMonge** [comment]
Hello I had tried with the binary and I compiled 1.5.1 RC2, also last stable of 1.4.1, but the look is the same.

![shot-2020-07-30_18-23-23](https://user-images.githubusercontent.com/1070783/88987054-f32b1800-d291-11ea-8641-eec5a31412e4.jpg)

**Comment by DanielGibson** [comment]
Hmm could you check whether the game data is complete (and correct), by comparing the MD5 sums of the .pk4's to https://dhewm3.org/#getting-the-doom3-game-data ? (And make sure there's no additional pk4s or other things in the base/ dir)
Just in case this is caused by corrupted fonts in the game or something similar

If that doesn't help I'm curious if d3wasm will work better :)

**Comment by EstebanMonge** [comment]
Looks correct:

emonge@angellodebiansofia:~/.local/share/dhewm3/base$ md5sum pak00*.pk4
71b8d37b2444d3d86a36fd61783844fe  pak000.pk4
4bc4f3ba04ec2b4f4837be40e840a3c1  pak001.pk4
fa84069e9642ad9aa4b49624150cc345  pak002.pk4
f22d8464997924e4913e467e7d62d5fe  pak003.pk4
38561a3c73f93f2e6fd31abf1d4e9102  pak004.pk4
2afd4ece27d36393b7538d55a345b90d  pak005.pk4
a6e7003fa9dcc75073dc02b56399b370  pak006.pk4
6319f086f930ec1618ab09b4c20c268c  pak007.pk4
28750b7841de9453eb335bad6841a2a5  pak008.pk4

**Comment by Yamagi** [comment]
@DanielGibson asked me if I could give this a try on my Radeon 5700XT. This is a fairly up to date Arch Linux with Linux 5.7.11, Mesa 20.1.4 and LLVM 10.0.1. I'm unable to reproduce the problem, both with the official binaries and the Debian binaries extracted from the deb. But this hasn't too much to say, the Raven APUs have Vega GPUs (gfx9) and the 5700XT is a Navi card (gfx10). That are different code paths in the DRM driver and another / altered shader compiler to generate 32 threads wide wavefront instead of 64 theads...

You could try to force SDMA to off and see if that helps: `AMD_DEBUG=nodma ./dhewm3`  
SDMA is known to be problematic and has been switched off by default some days ago: https://www.phoronix.com/scan.php?page=news_item&px=RadeonSI-Disables-GFX9-SDMA

**Comment by EstebanMonge** [comment]
Hello, I test with mesa 20.1.5 that already have SDMA disabled and it works!

Now I am prepared to shot to every monster that I will find! Thanks for the help

**Comment by EstebanMonge** [comment]
With mesa 20.1.5 the problem was gone.

**Comment by DanielGibson** [comment]
Awesome, I'm glad it works now!

(I like bugs that solve themselves =))
