### ISSUE TITLE
Too dark comparing with a similar mod

### ISSUE THREAD

**Issue by solarj** [dhewm/dhewm3#307]
Many parts of the game just are totally black, comparing with a weapon flash mod I used (http://neherson.narod.ru/). 

I suppose that a flashlight mod will not change too much of the game graphics when the flashlight is switched off, but the difference is significant: For example, in the beginning of the game when the player returned to mars city, a guy in the pipe room lowered the ladder to let player climb up, in dhewm3 mod, the player is totally merged in dark if not illuminated by flash light, but in flashlight mod, even without using flashlight, there are background lights illuminate him and you can see his body and face. The setting used to adjust intensity, brightness and gamma is irrelevant. The illumination is just not there

Is this intentionally made to increase the performance? Is there a setting to adjust this behavior?

**Comment by DanielGibson** [comment]
dhewm3 is not a mod, it's a source port and supposed to look and behave like the original (unmodded!) Doom3, except for small improvements for widescreen support and things like that.

I'm not sure I understand what you mean exactly - are you using that flashlight mod with original Doom3 or with dhewm3?
Also, what operating system are you on, what graphics card and driver are you using, which version of dhewm3 are you testing (1.5.1rc2 is the latest)?

I just tested that scene on Linux with just dhewm3 and with dhewm3 and yafm-hl.pk4 - it looked exactly the same.
Can you post screenshots to show what exactly you mean?
And (if you're on Windows where the original Doom3.exe still works okayish) can you try if it looks any different with original Doom3 1.3.1 (without that flashlight mod)?

This is what it looks like for me, no matter if I install that mod or not - though note that it looks a bit brighter in the game if gamma/brightness is increased, because it just increases the display gamma which isn't visible on screenshots:
![dhewm3-ladder-guy](https://user-images.githubusercontent.com/1216493/89112871-d5181000-d469-11ea-9567-e3c4e913ff24.jpg)
