### ISSUE TITLE
ROE will not load

### ISSUE THREAD

**Issue by MacDoomer** [dhewm/dhewm3#334]
Hi all,

Currently running dhewm3 1.5.0.1304 on macOS Catalina. The base game runs fine. When I try to start ROE, it does not load with the following error:

`ERROR: Function 'map_erebus1::main' not found in script for 'call' key on worldspawn`

I made sure that all the proper files are in the d3xp folder. I've tried using all of the contents of the d3xp folder as usual, as well as only the pak000.pk4 and pak001.pk4 files. Same error each time.

Other steps taken to resolve:

- Checked the md5 hashes for the pk4 files against the hashed on the Dhewm3 main page. They match.
- Checked the location of the pk4 files. Tried both the binary directory and the ~./doom3/d3xp folder and they both produce the same result. A review of the console indicates that the Dhewm3 binary is finding the pk4s and loading them properly.

**Comment by LETIshNick** [comment]
Hi,

I've just come here to report the same issue. It happens on High Sierra. [Here is the log](https://github.com/LETIshNick/errors_copypastas/commit/e85edcaa4856750bd13ec059a28590944a4e0052), hope it will be useful.

**Comment by DanielGibson** [comment]
I think these are different issues, as you don't have the `ERROR: Function 'map_erebus1::main' not found in script for 'call' key on worldspawn` error.

Where did you get your dhewm3 executable? Did you compile yourself? Might be worth trying the latest git code, there have been lots of changes since 1.5.0

@MacDoomer Do you have a `d3xp.dylib` next to your `base.dylib`? Also, can you post the whole terminal output?

@LETIshNick That looks like a bug in Apples OpenGL implementation, as you can see in the backtrace it's several calls deep in system OpenGL libs when the crash happens. Maybe upgrading to a newer macOS version would help, or maybe it would make it even worse, no idea.. though I heard that dhewm3 works even on Big Sur with ARM hardware (with this little change I merged a few weeks ago: https://github.com/dhewm/dhewm3/pull/322).

**Comment by LETIshNick** [comment]
@DanielGibson I've complied mine from dhewm3-1.5.1_RC2 repo. Unfortunately, the latest macOS available for my laptop is 10.13. I know about the dosdude's patcher but unfortunately this is my main machine now and I wouldn't like to tinker with it.

**Comment by DanielGibson** [comment]
Ok, that sucks :-/

The backtrace says something about precompressed images (which I think refers to s3tc compressed dds textures), you could try disabling them by starting dhewm3 with `./dhewm3 +set image_usePrecompressedTextures 0 +set image_useCompression 0`

If that still doesn't work you could try `+set image_downSize 1` and `+set image_ignoreHighQuality 1` which should reduce the texture quality (and thus how much GPU memory they need).

**Comment by LETIshNick** [comment]
@DanielGibson It worked, thank you!

The first set of commands allowed me to enter the roe's main menu, but game was failing nevertheless while trying to load any map. But the second set did the trick. My part of the issue is closed then.

**Comment by DanielGibson** [comment]
Awesome!

You could try setting Low/Medium/High video quality to maybe get the best possible (on your system) texture quality - but remember that whenever you change the video quality setting in that menu you need to make sure `image_usePrecompressedTextures` and `image_useCompression` are still `0` afterwards (by default the non-Ultra video modes use compressed textures).

**Comment by MacDoomer** [comment]
> @MacDoomer Do you have a `d3xp.dylib` next to your `base.dylib`? Also, can you post the whole terminal output?

Hi Daniel, thanks for the quick reply! I do not have a d3xp.dylib in my binary folder - just base.dylib and base-15.dylib.

I used a binary I found on Macrumors. https://forums.macrumors.com/threads/doom-3-for-catalina.2227497/.

I tried compiling from source, which did not return an error and produced a completed app file. However, it opens and closes immediately without providing feedback. I don't think it's a Gatekeeper problem.

The console log is attached.

[d3xperror.txt](https://github.com/dhewm/dhewm3/files/5612997/d3xperror.txt)

**Comment by DanielGibson** [comment]
> I do not have a d3xp.dylib in my binary folder

Yep, that's the problem (and the log confirms it with `WARNING: couldn't load mod-specific d3xp.dylib, defaulting to base game's library`) - RoE (aka d3xp) needs its own dylib to work, it has some new classes and functions and other changes the main game doesn't have.

I guess you could either ask in the forum if they could also provide a d3xp.dylib for the addon - or you could try compiling yourself again and try to make it work after all.
Unfortunately I can't be of much help because I don't own a Mac myself - maybe @LETIshNick has an idea if you need to do anything more with that .app file for the game to actually work?

**Comment by MacDoomer** [comment]
Hi @DanielGibson, I checked my build folder from my attempt to compile from source and there was a d3xp.dylib in there. After moving it into the folder for the binary I downloaded from MacRumors, it worked! Thank you for all the help. Closing as solved.

P.S. Let me say that I really appreciate your work on this project. You must have put many hours into it, and you've helped me play one of my favorite games again.

**Comment by DanielGibson** [comment]
Glad to hear it works now, have fun with it! :-)

**Comment by mkrupczak3** [comment]
On Ubuntu (not compiling from source), I found that ROE wouldn't launch. I'd get the following error:

`ERROR: Function 'map_erebus1::main' not found in script for 'call' key on worldspawn`

To fix this, I had to install the following package to obtain the missing `d3xp.so` binary:

`sudo apt install dhewm3-d3xp`

After that, everything worked!

This was in addition to the `dhewm3` and `dhewm3-doom3` packages
