### ISSUE TITLE
audio experince

### ISSUE THREAD

**Issue by martinbangens** [dhewm/dhewm3#355]
Hey, I love this project, game runs soo much smoother on linux. I feel the audio effect got a bit weak compared to the original. I don't get this "panic horror feeling" I love from this game. Audio seem a bit smoother(thats good) and less (like it creeps up on you). This can also be about taste, if its intended to be like this I guess this is not for me. If its not I feel like there could be a bit more punch or more compression. and also eax 4.0 don't feel realistic, especially with the volumes and echo. you get this effect like you would be in a "cylinder formed place" too much.

I couldn't do it better myself as I'm learning audio programing right now. hope no feeling are hurt. have the best day ever!!

**Comment by DanielGibson** [comment]
No feelings are hurt, but TBH I'm not sure what I should do about it :-P

This might be related to https://github.com/dhewm/dhewm3/issues/326 ?
In that ticket it turned out that the XBox version (and *maybe* early versions of Doom3?) sounded different than the official Doom3 1.3.1 or dhewm3

As far as I can tell dhewm3 sounds very similar to Doom3 1.3.1 (which is the goal of this source port)? If not, can you provide a video comparison or something like that which makes the differences clear?

I imagine that "fixing"/"improving" the audio experience would mean modifying the game **data**, not the code. Maybe the audio files themselves, maybe just the "sound shaders" (`sound/*.sndshd` in pak00*.pk4) and possibly the reverb definitions for the rooms of the maps (`efxs/*.efx`) for the EAX/EFX effects.
Maybe there are already mods or "sound packs" for Doom3 that make it sound more like you want it to?

**Comment by martinbangens** [comment]
I believe the sound was actually mono if you didn't activate stereo like in the sound card, some of those mono sound effect where really horrifying. I think the game today should be stereo. but with some of the "horrifying mono" (lol) effects left. like a balance between the two, and a bit less of those stereo surround effect. this is without EAX/EFX.

With EAX/EFX there could be just more "fine tuning" and especially these echo effects.

**Comment by j4reporting** [comment]
I usually disable EAX, because the effects with OpenAL does not sound right without a proper HRTF setup.  That being said, proper HRTF configuration seems to be science in itself.
see 
https://forums.thedarkmod.com/index.php?/topic/17689-improve-your-tdm-experience-by-playing-with-openal-soft-hrtf-better-3d-audio/
https://openal.org/pipermail/openal/2014-December/000274.html
https://steamcommunity.com/sharedfiles/filedetails/?id=2007414413

**Comment by martinbangens** [comment]
the audio should feel really evil and fuck with the player's head. for example when an enemy spawn these whispers should certainly be in mono like its coming from the players own head. and should not reveal where the enemy is at. as an example

**Comment by martinbangens** [comment]
yes of course, I seem like a way that only I want to go with audio :)
