### ISSUE TITLE
can't play music greater than 44.1khz

### ISSUE THREAD

**Issue by The-King-of-Toasters** [dhewm/dhewm3#380]
I transcoded the 48khz stereo version of Tweaker (link in description [here](https://www.youtube.com/watch?v=rs0cSUIKKew)) to ogg and put it in `base\sound\musical\d3theme.ogg`. When starting the game, it only plays a single beep, then silence. This doesn't happen when I resample it at 44.1khz.

**Comment by DanielGibson** [comment]
did you test this with 1.5.1 or latest git?
it's possible that neither works, but testing latest git might be worth a try. a recent build for win64 can be downloaded at [here](https://github.com/dhewm/dhewm3/files/6455471/dhewm3-1.5.2pre-win64-tools-msaa.zip)

**Comment by The-King-of-Toasters** [comment]
latest git, compiled by myself

**Comment by DanielGibson** [comment]
Sorry, forgot to reply.

Doom3 indeed only supports 44.1kHz (and 22 and 11 kHz, which are converted to 44.1kHz by duplicating samples), because all the internal code (including the mixer) are written for 44.1kHz.
While in theory with OpenAL this restriction shouldn't be needed anymore, changing this would be too much work because that 44.1kHz assumption is all over the place.

So yeah, you'll have to resample it to 44.1kHz - I doubt that the difference is noticeable when using a good resampler.
