### ISSUE TITLE
Brightness setting reverts to default

### ISSUE THREAD

**Issue by markanini** [dhewm/dhewm3#385]
In v1.5.1 changing the the brightness setting looses it's effect after five seconds, despite that the brightness slider looks modified in the options menu.

**Comment by DanielGibson** [comment]
What operating system and graphics card are you using?
Is it any different with 1.5.0 or 1.4.1?

**Comment by markanini** [comment]
I figured it out, it has to do with my system using X-Rite monitor calibration software, reverting the GPU gamma tables to it's own settings. The brightness setting works as intended when I close the X-Rite software.

This maybe begs the question, could the brightness control be implemented in the engine instead of the GPU?

If you a still wondering I tested v1.5 with the same result, under Windows 10 on a 1050ti.

**Comment by nbohr1more** [comment]
I think you are asking whether gamma can be controlled via shaders rather than direct hardware control? We implemented this in TDM so it is possible but it lead to a little bit of acrimony since (for us) gamma controls both GUI and GUI shader effects like water overlays.

**Comment by DanielGibson** [comment]
Controlling gamma via shaders is possible (and easy) *generally*, but in Doom3s case it would probably mean runtime-patching the existing shaders (that use that weird ARB syntax) which is a bit harder, I think.

I'll look into it - in fact just yesterday I thought about it because I was pissed about the screens gamma (sometimes?) remaining changed if dhewm3 is crashing (or terminated in debugger). Can't promise anything though..

**Comment by nbohr1more** [comment]
Before we went to GLSL ( TDM 2.04 and earlier ) we offered a postprocess ARB shader controlled by a custom r_postprocess_gamma cvar. Feel free to use this shader in your design though it might not be the best implementation because it was only designed to modulate the "HDR-Lite" bloom feature we added in 1.03

**Comment by emileb** [comment]
I linked the 'brightness' slider to make the dynamic lights brighter instead of changing gamma (which isn't available on mobile).
Obviously it looks different to altering gamma but I actually think the effect looks better. May be a quick option.

(See RB_overbright variable)

https://github.com/emileb/d3es-multithread/blob/b82376d7d2a6217aea4b384bb02da65508ae8951/neo/renderer/RenderSystem_init.cpp#L1328

https://github.com/emileb/d3es-multithread/blob/b82376d7d2a6217aea4b384bb02da65508ae8951/neo/renderer/tr_render.cpp#L312

**Comment by DanielGibson** [comment]
I'm thinking about passing r_brightness and `1.0/r_gamma` as env (uniform) into the fragment shaders, replace `result.color` with a temporary `dhewm3tmpres` variable (via string replace) and do the ARB shader equivalent of
`result.color.rgb = pow(dhewm3tmpres.rgb*vec3(r_brightness), vec3(1.0/r_gamma));`
at the end to do the full brightness and gamma correction in the shader (I *think* this is equivalent to what the gamma ramp generated by Doom3 does).

In Yamagi Quake2's GL3 render I already basically do the same: https://github.com/yquake2/yquake2/blob/master/src/client/refresh/gl3/gl3_shaders.c#L402-L405
(note that `gamma` in those shaders is really `1.0/gamma`)

I'm not sure how well that's gonna work, at least one potential problem is that in case of rendering to a texture and then using that texture again in a shader (postprocess effects?) brightness/gamma could be applied twice - but maybe I can detect and work around those cases (in YQ2 this is no problem because there are no postprocess shaders or similar).

BTW, your d3es-multithread sounds super interesting - but as far as I understand it only works on Android, do you think it would be hard to make it work on "normal" Linux? I'd love to try it on my Raspberry Pi 4 (where the performance of "normal" dhewm3 and d3wasm is very bad).

**Comment by emileb** [comment]
> I'm thinking about passing r_brightness and `1.0/r_gamma` as env (uniform) into the fragment shaders, replace `result.color` with a temporary `dhewm3tmpres` variable (via string replace) and do the ARB shader equivalent of
> `result.color.rgb = pow(dhewm3tmpres.rgb*vec3(r_brightness), vec3(1.0/r_gamma));`
> at the end to do the full brightness and gamma correction in the shader (I _think_ this is equivalent to what the gamma ramp generated by Doom3 does).
> 
> In Yamagi Quake2's GL3 render I already basically do the same: https://github.com/yquake2/yquake2/blob/master/src/client/refresh/gl3/gl3_shaders.c#L402-L405
> (note that `gamma` in those shaders is really `1.0/gamma`)
> 
> I'm not sure how well that's gonna work, at least one potential problem is that in case of rendering to a texture and then using that texture again in a shader (postprocess effects?) brightness/gamma could be applied twice - but maybe I can detect and work around those cases (in YQ2 this is no problem because there are no postprocess shaders or similar).

Yes sound like it should work, for sure could detect when rendering to the screen and only apply it there.

Just reminded me I also added an option to render to a renderbuffer to allow the render resolution to be anything: 
https://github.com/emileb/d3es-multithread/blob/master/neo/renderer/framebuffer.cpp

Gamma could probably be used with something like that. It might actually fit in easily to your code base, just need to init then call R_FrameBufferStart() and R_FrameBufferEnd() at appropriate places and it *might* work.

> 
> BTW, your d3es-multithread sounds super interesting - but as far as I understand it only works on Android, do you think it would be hard to make it work on "normal" Linux? I'd love to try it on my Raspberry Pi 4 (where the performance of "normal" dhewm3 and d3wasm is very bad).

Yeah I have been meaning to allow it to build for Linux, there isn't actually any reason it won't work I just need to remove the mobile specific crap and fix the make files. I've not got a Raspberry Pi 4 yet but I see it quite a bit more powerful than the 3. 
The multithreading can add about 40% performance, seems to really depend on the system and how the CPU/GPU loading split is probably 1000 other variables!

**Comment by markanini** [comment]
Not sure if it's useful for this project but I'm liking the image quality I'm getting with this reshade shader https://github.com/prod80/prod80-ReShade-Repository/blob/master/Shaders/PD80_03_Curved_Levels.fx

**Comment by DanielGibson** [comment]
I implemented something: https://github.com/dhewm/dhewm3/tree/gamma-in-shader
Not tested all that much yet

**Comment by DanielGibson** [comment]
Windows binaries: [dhewm3-1.5.2pre-win32-shadergamma.zip](https://github.com/dhewm/dhewm3/files/6652492/dhewm3-1.5.2pre-win32-shadergamma.zip)

This should probably be extensively tested (with Doom3, D3XP and supported mods) - please let me know if it works (or not)!

**Comment by markanini** [comment]
On a quick test it seem to be working well.

**Comment by DanielGibson** [comment]
If on Windows the game freezes (so far only observed with *The Lost Mission*), as a workaround you can set `win_outputEditString 0` in the console (or `+set win_outputEditString 0` as commandline argument when starting dhewm3).

I'm working on a proper fix.
(This issue has nothing to do with this brightnes/gamma feature but was introduced when I replaced libogg/vorbis with stb_vorbis and added some logmessages when decoding an ogg fails - which unfortunately happens in the async thread and logging in that thread can lead to a deadlock)

**Comment by DanielGibson** [comment]
I'll close this issue, further discussion (and possibly updated Windows builds) are in the pull request: https://github.com/dhewm/dhewm3/pull/387
