### ISSUE TITLE
Submit app to Flathub

### ISSUE THREAD

**Issue by Eonfge** [dhewm/dhewm3#389]
Related to: #388 

I'm in the process of submitting Dhewm3 to Flathub, a universal and modern distribution framework for Linux. Since it's your project though, I think it's important to also get your feedback and to discuss this directly with you.

- Do you wish to engage directly with Flathub?
- Do you want maintainer status on the Flatpak package?

I'm not sure how much you know about Flatpak, Flathub, and similar, so please feel free to ask me anything.

**Comment by DanielGibson** [comment]
I don't mind if you submit dhewm3 to flathub, but I don#t want to engange directly with it or be maintainer there, as being maintainer here already is enough work (and I don't use flatpak myself) :-)
I don't know how it works with flathub, but I'd prefer if in case of bugs people would first report them there in case it's issues due to the build or something - like it is, or should be, the case on Linux distributions packages where bugs should be reported in the distros bugtracker first, and maintainers then take the reports upstream if necessary.

BTW:
> The name Dhewm 3 must be a reference to this great review of Zero Punctuation btw;
> https://www.youtube.com/watch?v=HQGxC8HKCD4

The reason is even simpler: This project was started by [*dhewg*](https://github.com/dhewg). He originally wanted to get his work into iodoom3, but as that didn't take off he made his own fork/source port and called it *dhewm*.

**Comment by Eonfge** [comment]
Flathub has been approved!
https://flathub.org/apps/details/org.dhewm3.Dhewm3

Thanks for your cooperation so far.
