### ISSUE TITLE
Can't get EAX working

### ISSUE THREAD

**Issue by vorob1** [dhewm/dhewm3#512]
Actually i don't even see that i need to do smth for it to work so I turn it ON and after requested relaunch it's OFF again. 

I've installed this ancient thing from 2009 to my Windows 11, but no luck (https://openal.org/downloads/)

Feel myself really silly, sorry.

**Comment by vorob1** [comment]
Maybe i'm doing smth wrong?

**Comment by DanielGibson** [comment]
You shouldn't have to install anything (besides dhewm3), because the official dhewm3 windows builds ship their own OpenAL32.dll that should work with any sound hardware and support EAX-like effects via EFX.
You should be able to enable it in Options -> System by switching "EAX 4.0 HD" to "On", applying the changes and restarting the game.

**Comment by vorob1** [comment]
LOL! Just checked it once again and it's working! Sorry for bothering you.

**Comment by DanielGibson** [comment]
glad it works, have fun with the game :)
