### ISSUE TITLE
Extreme Frame Drops (Unplayable) in Maintenance Area Below Satellite Area

### ISSUE THREAD

**Issue by Graham1225** [dhewm/dhewm3#521]
This is a great source port. Fantastic way to play the game on my M1 2020 Macbook Air. I played through the game once already. However, on my second playthrough, as soon as I hit the Maintenance section just prior to Monorail, the game starts to drop frames horribly i.e. the screen changes to a new frame every 5 seconds. I have no clue what causes it. I reinstalled and tried again with the old save, but the issue persisted. Any ideas?

**Comment by DanielGibson** [comment]
I'm not sure which place you mean exactly, can you take a screenshot?
I played through all of Recycling2 and then went on to the Monorail level and rode the monorail, without any issues.
But that was on my Linux desktop PC with a nvidia GPU, I don't have a Mac.

One thing you could try is loading that level via console and see if you get the same problem again (=> if it's not specific to your savegame).
You can open (and later close) the console with `Shift`+`Esc` and then enter `map game/recycling2.map`. After loading the map, you will probably want to enter `give all` in the console to get all weapons with full ammo, otherwise you may not have enough ammonition to beat the level (unlike in normal playthroughs, you don't have all the ammonition you otherwise would've collected in the previous levels).

If you get the same frame drops then, it's likely a bug in Apple's OpenGL driver (maybe even only the one for M1).

**Comment by packetwar** [comment]
Same issue here on an M2 Mac. The actual level is Communications near the end. You send the transmission then take the elevator down to Maintenance. As soon as the door opens, a Z-Sec and Imp attack you. This is right when the frames drop to less than 1 per every 5 seconds. When you go into the next room with the two imps and the bridge, same behavior. You reach the other side of the bridge and enter another small area and there’s another Z-Sec and imp, same behavior as well. If I remember correctly, the issue seemed to go away after I got in the other elevator and rode back up to Communications just before exiting the level. I didn’t see any console warnings other than some missing sounds. Also, audio seems to play fine during the graphical stuttering.

**Comment by Swiss-Mac-User** [comment]
> …as soon as I hit the Maintenance section just prior to Monorail, the game starts to drop frames horribly i.e. the screen changes to a new frame every 5 seconds.

> Same issue here on an M2 Mac. The actual level is Communications near the end. You send the transmission then take the elevator down to Maintenance. As soon as the door opens, a Z-Sec and Imp attack you. This is right when the frames drop to less than 1 per every 5 seconds. When you go into the next room with the two imps and the bridge, same behavior. You reach the other side of the bridge and enter another small area and there’s another Z-Sec and imp, same behavior as well.

I _cannot_ reproduce these slow-downs in the said areas. I tested this with the [Mac Source Port version of dhewm 3 (1.5.2)](https://github.com/macsourceports/dhewm3).

Specs:
* dhewm 1.5.2 (Mac Source Port)
* MacBook Pro M2
* macOS Sonoma 14.4 Beta
* 32 GB Memory, 12 Performacne Cores, 38 GPU Cores (Apple M2 Max)
* Doom 3 Graphic Settings: Ultra High & uncapped Frame Rates (
