### ISSUE TITLE
Shadows are broken in dhewm 1.5.2

### ISSUE THREAD

**Issue by shamazmazum** [dhewm/dhewm3#522]
Hi! I use FreeBSD 13.2 with sway 1.8.1, mesa 22.3.7 and AMD Radeon RX 500-series card (580, I believe). Until recently, dhewm3 worked fine, but now I have broken shadows (as you can see on the screenshots).

Any idea how to fix this? Looks like some FP math errors. Also I cannot find where shaders are located. Can you point me to them?

![20230625_11h40m01s_grim](https://github.com/dhewm/dhewm3/assets/812069/7b437fcf-4e50-4f42-9637-ea9b3dd5522f)
![20230625_11h42m32s_grim](https://github.com/dhewm/dhewm3/assets/812069/f447a6f9-1e5e-42f4-bd06-c6eec7123bdc)

**Comment by DanielGibson** [comment]
The shaders are in pak000.pk4 (pk4 is zip really, so you can open it with archive managers or plain `unzip`) under glprogs/

However, Doom3/dhewm3 uses stencil shadows which are calculated on the CPU, so I don't think shaders have much to do with it (though it could still be a GPU driver bug, because in the end they're rendered by the GPU, of course).

Have you tried building an older version of dhewm3 - if so, does it cause the same issues?
(The only time I've ever changed anything about shadow rendering was when reintroducing "Carmack's Reverse" Z-fail stencil shadows in 1.5.1, where I also introduced using `glStencilOpSeparate()`. You should get the old behavior by setting the CVars `r_useCarmacksReverse` and `r_useStencilOpSeparate` to `0`.)

**Comment by shamazmazum** [comment]
Turns out, this bug is fixed in 957176d. Maybe it's worth considering the new release?

**Comment by DanielGibson** [comment]
Good to know!

> Maybe it's worth considering a new release?

yeah, maybe.. it's always so much work, and there's always one more feature one wanted to add before the next release... ;)
