### ISSUE TITLE
weird error loading the game lib

### ISSUE THREAD

**Issue by BielBdeLuna** [dhewm/dhewm3#570]
here is the error message:

```
WARNING: Failed to load lib '/home/biel/games/doom/doom3/base.so' even though it exists and is readable! Reason: /home/biel/games/doom/doom3/base.so: undefined symbol: _Z8vsprintfR5idStrPKcP13__va_list_tag


WARNING: couldn't load mod-specific base.so, defaulting to base game's library!

WARNING: Failed to load lib '/home/biel/games/doom/doom3/base.so' even though it exists and is readable! Reason: /home/biel/games/doom/doom3/base.so: undefined symbol: _Z8vsprintfR5idStrPKcP13__va_list_tag

Regenerated world, staticAllocCount = 0.
shutting down: couldn't load game dynamic library
Shutting down sound hardware
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
Sys_Error: couldn't load game dynamic library
shutdown terminal support

```

recompiled twice and still i get this error.

what is? "_Z8vsprintfR5idStrPKcP13__va_list_tag" ? a malformed printing stuff? maybe this is an optimitzation issue?

**Comment by DanielGibson** [comment]
There must be something broken on your system.

I didn't change anything that would explain this problem since you made your `in_namePressed` pull request (when loading base.so still worked, or you couldn't really have tested your code?) and it works on my system.

```
$ c++filt _Z8vsprintfR5idStrPKcP13__va_list_tag
vsprintf(idStr&, char const*, __va_list_tag*)
```

so it's this function: https://github.com/dhewm/dhewm3/blob/b565c6c7326b46905e679b297dc666abd929dd6f/neo/idlib/Str.cpp#L1593

I don't see why it shouldn't be found (idlib is linked statically into base.so). Maybe there's something wrong with your linker or compiler.

**Comment by BielBdeLuna** [comment]
deleted it all and re-cloned it again and now it worked fine! it was an error on my end... sorry
